### ISSUE TITLE
windows issue

### ISSUE THREAD

**Issue by Gandrushka** [werdeil/itunes-last-export#10]
so i got to try script in windows. it doesn't work

`C:\>itunes-last-export
Traceback (most recent call last):
  File "C:\Users\Gandrushka\AppData\Local\Programs\Python\Python38-32\Scripts\itunes-last-export-script.py", line 11, in <module>
    load_entry_point('itunes-last-export==0.0.6', 'console_scripts', 'itunes-last-export')()
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\itunes_last_export\__init__.py", line 9, in <module>
    import itunes_last_export.update_playcount
  File "c:\users\gandrushka\appdata\local\programs\python\python38-32\lib\site-packages\itunes_last_export\update_playcount.py", line 22, in <module>
    from Foundation import *
ModuleNotFoundError: No module named 'Foundation'`

**Comment by werdeil** [comment]
Indeed as I said this was developed on macOS and I was hoping it to work also on windows. The issue here is that I use the Foundation lib which is not include in Windows I guess. I'll be explicit on the fact that this is working only on MacOS.
