### ISSUE TITLE
error on Mojave: ModuleNotFoundError: No module named 'server_management'

### ISSUE THREAD

**Issue by koenige50** [werdeil/itunes-last-export#11]
On Mac OS Mojave, with Python 3.9.2 installed through Homebrew, while trying to launch itunes-last-export I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/itunes-last-export", line 5, in <module>
    from itunes_last_export.gui import main
  File "/usr/local/lib/python3.9/site-packages/itunes_last_export/__init__.py", line 9, in <module>
    import itunes_last_export.update_playcount
  File "/usr/local/lib/python3.9/site-packages/itunes_last_export/update_playcount.py", line 25, in <module>
    from server_management import lastexporter
ModuleNotFoundError: No module named 'server_management'
```

I checked and the file /usr/local/lib/python3.9/site-packages/itunes_last_export/server_management.py does exist, but apparently it's not being recognised.

Thank you for this package, which seems just what I need, once I am able to get it running.

**Comment by werdeil** [comment]
I'll try to reproduce this weekend, I'll keep you posted

**Comment by johnrobertshepherd** [comment]
This happens on Big Sur too: I have tried it with Python installed via Homebrew and installed directly.

**Comment by koenige50** [comment]
> I'll try to reproduce this weekend, I'll keep you posted

Did you check this in the end? Were you able to reproduce the problem? I am still suffering from it in Mac OS Catalina with python 3.9/3.10 installed via Homebrew.
